### ISSUE TITLE
Help with connecting two or more board relays with esphome rs485

### ISSUE THREAD

**Issue by Kentrp** [kecajtop/dtr0xx_io#2]
Hi! I use your esphome .yaml code  to flash my 8 relays boards, its work fine, but now i want to connect them between themselves with RS485 2 wires (i want to connect one master board to Ethernet and other boards to connect to the master use RS485 port) , and don't know how to do it, ill be appreciate you to help me, thank you

**Comment by kecajtop** [comment]
Hi!
Esphome is natlivly supporting RS485 master side. That stuff is very easy to do. I have done it before

sensor:
  - platform: modbus_controller
    modbus_controller_id: epever
    name: ${friendly_name} Temperature
    id: temperature
    register_type: read #0x04
    address: 0x0001
    unit_of_measurement: "C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
    
To use esphome as a modbus slave is more ticky. You need modbus server.

modbus_server:
  - id: modbuserver
    uart_id: mod_bus
    flow_control_pin: 33
    address: 2 # slave address
    holding_registers:
      - start_address: 79 # starting register range
        default: 82 # default value for all those registers
        number: 10 # number of registers in the range
        on_write: |
          ESP_LOGI("ON_WRITE", "This is a lambda. address=%d, value=%d", address, value);
          return value;
        on_read: | # called whenever a register in the range is read
          // 'address' contains the requested register address
          // 'value' contains the stored register value 
          ESP_LOGI("ON_READ", "This is a lambda. address=%d, value=%d", address, value);
          return value; // you can return the stored value or something else.
      - start_address: 200 # in this example we map register 200 to a switch
        number: 1
        on_write: |
          if(value)
            id(relay_1)->turn_on();
          else
            id(relay_1)->turn_off();
          ESP_LOGI("ON_WRITE", "This is a lambda. address=%d, value=%d", address, value);
          return value;
        on_read: |
          ESP_LOGI("ON_READ", "This is a lambda. address=%d, value=%d", address, value);
          return value;

It will require few tries and errors. Debuging will be very helpulf (ESP_LOGI). Additional RS485 to USB cable might be also requaried. Sorry if I cannot be more helful but my board is not accesable at this time so I cannot make any mockups to test it.

**Comment by Kentrp** [comment]
Hello! I need one more help, how to write binary sensors  and sensors in modbusserver i can't get it work correct, thank you

**Comment by kecajtop** [comment]
Hi,

What would be your address and register number?

**Comment by Kentrp** [comment]
It's doesn't matter i just need example

**Comment by Kentrp** [comment]
modbus_server:
  - id: modbuserver
    uart_id: mod_bus
    address: 2 # slave address
    holding_registers:
      - start_address: 79 # starting register range
        default: 82 # default value for all those registers
        number: 10 # number of registers in the range
        on_write: |
          ESP_LOGI("ON_WRITE", "This is a lambda. address=%d, value=%d", address, value);
          return value;
        on_read: | # called whenever a register in the range is read
          // 'address' contains the requested register address
          // 'value' contains the stored register value
          ESP_LOGI("ON_READ", "This is a lambda. address=%d, value=%d", address, value);
          return value; // you can return the stored value or something else.
      - start_address: 200 # in this example we map register 200 to a switch
        number: 1
        on_write: |
          if(value)
          id(relay_1)->turn_on();
          else
          id(relay_1)->turn_off();
          ESP_LOGI("ON_WRITE", "This is a lambda. address=%d, value=%d", address, value);
          return value;
        on_read: |
          ESP_LOGI("ON_READ", "This is a lambda. address=%d, value=%d", address, value);
          return value;
      - start_address: 201 # in this example we map register 200 to a switch
        number: 1
        on_write: |
          if(value)
          id(relay_2)->turn_on();
          else
          id(relay_2)->turn_off();
          ESP_LOGI("ON_WRITE", "This is a lambda. address=%d, value=%d", address, value);
          return value;
        on_read: |
          ESP_LOGI("ON_READ", "This is a lambda. address=%d, value=%d", address, value);
          return value;
      - start_address: 202 # in this example we map register 200 to a switch
        number: 1
        on_write: |
          if(value)
          id(relay_3)->turn_on();
          else
          id(relay_3)->turn_off();
          ESP_LOGI("ON_WRITE", "This is a lambda. address=%d, value=%d", address, value);
          return value;
        on_read: |
          ESP_LOGI("ON_READ", "This is a lambda. address=%d, value=%d", address, value);
          return value;

**Comment by kecajtop** [comment]
Did you soved this problem?

**Comment by Kentrp** [comment]
> Did you sove this problem?

Yes, Thank you

**Comment by Kentrp** [comment]
No, i don't know if it possible to do, i want to use pin for Dallas 18b20 sensor

**Comment by kecajtop** [comment]
Are you good in soldering?

**Comment by Kentrp** [comment]
> Are you good in soldering?

Yes I am

**Comment by kecajtop** [comment]
Are we still talking about modbus problem or just temp sensor? Are you using ethernet port as well or just wifi?

**Comment by Kentrp** [comment]
Yes want to connect sensor to relay and if it possible to send data from one to another relay using rs485 ( modbus)

**Comment by Kentrp** [comment]
I use ethernet in one relay and wifi in another one

**Comment by kecajtop** [comment]
You might need to use spear pins. I did that before for i2c display

i2c:
  sda: 4
  scl: 5
  scan: true
  id: bus_a
  frequency: 400kHz

so for dallas chip

sensor:
  - platform: dallas
    address: 0x5f000000560bdf28 # id can be obtained from logs on first boot
    name: ${friendly_name} Temperature

dallas:
  - pin: GPIO4
    update_interval: 10s

**Comment by kecajtop** [comment]
Or you can use RX pin 
![image](https://github.com/kecajtop/dtr0xx_io/assets/16417187/4e36ef9d-6e65-47e6-aad2-8455c2e3b594)

**Comment by Kentrp** [comment]
It’s mean to connect dallas sensor to i2c pin 4 data wires?

**Comment by Kentrp** [comment]
> Or you can use RX pin ![image](https://private-user-images.githubusercontent.com/16417187/293258134-4e36ef9d-6e65-47e6-aad2-8455c2e3b594.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3ODg5MDIsIm5iZiI6MTcwMzc4ODYwMiwicGF0aCI6Ii8xNjQxNzE4Ny8yOTMyNTgxMzQtNGUzNmVmOWQtNmU2NS00N2U2LWFhZDItODQ1NWMyZTNiNTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDE4MzY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZDY1YjMzNDg2NGMwNmQyM2EzZTk5NDE5ZTBjZTYwMWNlMWRiNTFiNTNkYjk1ODMzMTJlMTgyZmUzMjJkZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6loEHpR-D0wrz4KKZPikMXHVvmQqOZHbzE827MnIvUk) you just need to disable uart logs

I used this pins in other projects like binary sensor and relay after power off dead i need to reflash it

**Comment by Kentrp** [comment]
Im interesting to use input to connect sensors

**Comment by kecajtop** [comment]
try to use pin 4
platform: dallas
address: 0x5f000000560bdf28 # id can be obtained from logs on first boot
name: ${friendly_name} Temperature
dallas:

pin: GPIO4
update_interval: 10s

![image](https://github.com/kecajtop/dtr0xx_io/assets/16417187/fd67b8d8-4e04-4ee7-a3a4-a3d00966adbc)

**Comment by Kentrp** [comment]
We’re is pin 4 in relay

**Comment by kecajtop** [comment]
![image](https://github.com/kecajtop/dtr0xx_io/assets/16417187/400b1709-a583-41f0-a76a-04c117690aa4)
bottom left corner

**Comment by kecajtop** [comment]
I will try dallas pin tomorrow. My unit is not easly accessible.

**Comment by kecajtop** [comment]
I made some progress last evening. I was able to send some intigiger value of the internal temp sensor via modbus.

**Comment by kecajtop** [comment]
![image](https://github.com/kecajtop/dtr0xx_io/assets/16417187/be2ae294-09e4-4f89-a19c-a43acdb6b9d6)

**Comment by kecajtop** [comment]
modbus_server:
  - id: modbuserver
    uart_id: mod_bus
    flow_control_pin: 33
    address: 2 # slave address
    holding_registers:
      - start_address: 79 # starting register range
        default: 82 # default value for all those registers
        number: 10 # number of registers in the range
        on_write: |
          ESP_LOGI("ON_WRITE", "This is a lambda. address=%d, value=%d", address, value);
          return value;
        on_read: | # called whenever a register in the range is read
          // 'address' contains the requested register address
          // 'value' contains the stored register value 
          ESP_LOGI("ON_READ", "This is a lambda. address=%d, value=%d", address, value);
          return value; // you can return the stored value or something else.
      - start_address: 200 # in this example we map register 200 to a switch
        number: 1
        on_write: |
          if(value)
            id(relay_1)->turn_on();
          else
            id(relay_1)->turn_off();
          ESP_LOGI("ON_WRITE", "This is a lambda. address=%d, value=%d", address, value);
          return value;
        on_read: |
          return (id(temp_sens1).state)*100;

sensor:
  - platform: dallas
    address: 0x000000000000000 # id can be obtained from logs on first boot
    name: ${friendly_name} Temperature
    id: temp_sens1
  
dallas:
  pin: GPIO4
  update_interval: 10s

**Comment by kecajtop** [comment]
![image](https://github.com/kecajtop/dtr0xx_io/assets/16417187/47d06a68-133e-4de0-a4ee-5b9f3012e414)

**Comment by Kentrp** [comment]
> modbus_server:
> 
> * id: modbuserver
>   uart_id: mod_bus
>   flow_control_pin: 33
>   address: 2 # slave address
>   holding_registers:
>   
>   * start_address: 79 # starting register range
>     default: 82 # default value for all those registers
>     number: 10 # number of registers in the range
>     on_write: |
>     ESP_LOGI("ON_WRITE", "This is a lambda. address=%d, value=%d", address, value);
>     return value;
>     on_read: | # called whenever a register in the range is read
>     // 'address' contains the requested register address
>     // 'value' contains the stored register value
>     ESP_LOGI("ON_READ", "This is a lambda. address=%d, value=%d", address, value);
>     return value; // you can return the stored value or something else.
>   * start_address: 200 # in this example we map register 200 to a switch
>     number: 1
>     on_write: |
>     if(value)
>     id(relay_1)->turn_on();
>     else
>     id(relay_1)->turn_off();
>     ESP_LOGI("ON_WRITE", "This is a lambda. address=%d, value=%d", address, value);
>     return value;
>     on_read: |
>     return (id(temp_sens1).state)*100;
> 
> sensor:
> 
> * platform: dallas
>   address: 0x000000000000000 # id can be obtained from logs on first boot
>   name: ${friendly_name} Temperature
>   id: temp_sens1
> 
> dallas: pin: GPIO4 update_interval: 10s
Hi can it send more then 1 data sensors through modbus

**Comment by kecajtop** [comment]
![image](https://github.com/kecajtop/dtr0xx_io/assets/16417187/909b6b79-0b1a-4737-a38a-59eac287b818)

**Comment by kecajtop** [comment]
Did it work?
