### ISSUE TITLE
Problem with Esphome firmware upload

### ISSUE THREAD

**Issue by pacitzu** [kecajtop/dtr0xx_io#3]
Which programmer do you use to upload the Esphome firmware?
CP210x USB to UART converter?
Ch340g USB to UART converter?
Esp-prog JTAG Downloader?

I'm using the "web.esphome.io" site and a "CP210x USB to UART" converter. The Dingtian board is the developer version.
A serial connection with the card begins but the firmware upload does not start.
A suggestion?
Thanks

**Comment by kecajtop** [comment]
The ESP32 will enter the serial bootloader when GPIO0 is held low on reset. Otherwise it will run the program in flash.

**Comment by kecajtop** [comment]
Also ESP32 is 3.3V device.

**Comment by kecajtop** [comment]
But in my case I did use ch340 and ftdi chip. It should'n make any difference which usb conveter you will be using as long is working.

**Comment by pacitzu** [comment]
Thank you very much. I solved.
the problem was that GPIO0 was not kept low upon reset
