### ISSUE TITLE
problem after update

### ISSUE THREAD

**Issue by Kentrp** [kecajtop/dtr0xx_io#5]
Hi I have a problem after update Esphome. I send a log. Can you fix it. Thank you
[logs_garden-irrigation-1_run.txt](https://github.com/kecajtop/dtr0xx_io/files/13767238/logs_garden-irrigation-1_run.txt)

**Comment by kecajtop** [comment]
Try it now. It will require allow_other_uses: true flag with each dtr0xx_io component gpio.

**Comment by Kentrp** [comment]
> Try it now. It will require allow_other_uses: true flag with each dtr0xx_io component gpio.

You cod is ok, but you have to add 'allow_other_uses: true' to pin13 too
    dingtian_sdi_pin: 
      number: 13
      mode: 
        output: True
        input: False
        open_drain: False
        pullup: False
        pulldown: False
      inverted: False
      ignore_strapping_warning: False
      drive_strength: 20.0
      allow_other_uses: true

**Comment by kecajtop** [comment]
Do you have 16 channel version?

**Comment by eknower** [comment]
I have the 16 channel version, and I'm also waiting for your new release (I haven't tried the one you posted yesterday yet). If you need me to help with QA, I'll be happy to. Thanks again for the effort!

**Comment by kecajtop** [comment]
It should work as far I know, No changes to c++ component. Just update of python script.
